spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatis?serverTimezone=UTC
    username: root
    password: 123456


  mvc:
    view:
      prefix: WEB-INF/jsp/
      suffix: .jsp

#编码格式
  http:
    encoding:
      charset: utf-8
      enabled: true
      force: true

server:
  tomcat:
    uri-encoding: UTF-8


mybatis:
  config-location: classpath:cfg/mybatis-cfg.xml
  mapper-locations: classpath:mapper/user-mapper.xml








